FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Polls
Lets describe polls!

# Group Questions
Resources related with questions.

## Question Collection [/questions]

### List all Questions [Get]
+ Response 200 (application/json)
