FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Polls
Lets describe polls!

# Group Questions
Resources related with questions.

## Question Collection [/questions]

### List all Questions [GET]

Info regarding GET request


+ Request (application/json)

+ Response 200 (application/json)

        [
            {
                "question": "Are u ok?",
                "published_at": "2014-11-11T08:40:51.620Z",
                "url": "/questions/1",
                "choices": [{
                    "choice": "Swift",
                    "url": "/questions/1/choices/1",
                    "votes": 2048
                }, {
                    "choice": "Python",
                    "url": "/questions/1/choices/2",
                    "votes": 1024
                }, {
                    "choice": "Objective-C",
                    "url": "/questions/1/choices/3",
                     "votes": 512
                }, {
                    "choice": "Ruby",
                    "url": "/questions/1/choices/4",
                    "votes": 256
                }]
            }
        ]

### Create a Question [POST]
You may create your own question.
Accepts a JSON with a question and more then one choices.

+ question (string) - The text of the question
+ choices (array[string]) - The possible anwsers

+ Request (application/json)

    + Headers

            Location: /questions/1
            X-Something: 'Lalala'

    + Body

            {
                "question": "Favourite programming language?",
                "choices": [
                    "Swift",
                    "Python",
                    "Objective-C",
                    "Ruby"
                ]
            }

+ Response 201 (application/json)

    + Headers

            Location: /questions/1
            X-Something: 'Lalala'
    + Body

            {
                "hello": "hi",
                "choices": [1, 2, 3]
             }


## Question [/questions/{question_id}]

    + Parameters

            + question_id (number) - ID of the question.

### View a Questions Detail [GET]
Multiple responses:
+ 200 - Everything is ok
+ 404 - If there is no question with the particular ID
+ Response 200 (application/json)

            {
                "question": "Text me?"
            }
+ Response 404

            {
                "404": "Not found"
            }

### Delete [DELETE]
+ Response 204